name: '📊 Auto Update README Stats'

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        
    - name: 🔄 Update README Stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_LINES_OF_CODE: "True"
        SHOW_PROFILE_VIEWS: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "True"
        SHOW_PROJECTS: "True"
